// <auto-generated />
using Lab2_v3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab2_v3.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab2_v3.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName");

                    b.Property<int>("Population");

                    b.Property<string>("ProvinceCode");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Lab2_v3.Models.Province", b =>
                {
                    b.Property<string>("ProvinceCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.Property<string>("ProvinceName");

                    b.HasKey("ProvinceCode");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Lab2_v3.Models.City", b =>
                {
                    b.HasOne("Lab2_v3.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode");
                });
#pragma warning restore 612, 618
        }
    }
}
